### PR TITLE
It is actually fairly easy to do a live update of the window....

### PR DESCRIPTION
**Pull request by elangelo**
just grab the window while dragging over the grid and resize on the fly...

### CODE REVIEW

**Comment by elangelo** [comment]
@bjorn-fischer This works actually spectacularly well... i know i just copy pasted some code now to make it work...
2 questions.
1. want to move that code in a function to avoid repeating ourselves?
2. do you want this one to be optional with an argument

i guess 3 is if you even want this at all :)

**Comment by bjorn-fischer** [comment]
The closer you look the less easy it becomes:
- Live geometry updates need to be separated from the mouse_move event. This should be triggered by a custom signal that is emitted on actual changes of the rect object or, at least, happen within a contitional code path.
- The cursor Gt.DrawingArea should be disabled while live geometry update mode is active.
- When gridlock is canceled via keyboard or mouse button, the original geometry should be restored.
- There are X11 clients that ignore or do not react well to rapid geometry changes, so there should be a way to exclude live updates for clients by window classes and/or window name patterns
- This feature should be optional with default-off

**Comment by elangelo** [comment]
> The closer you look the less easy it becomes:
> 
>     * Live geometry updates need to be separated from the mouse_move event. This should be triggered by a custom signal that is emitted on actual changes of the rect object or, at least, happen within a contitional code path.
> 
I suppose you mean only want to send a resize when the actual rectangle where the mouse is actually did change?

>     * The cursor Gt.DrawingArea should be disabled while live geometry update mode is active.
I guess I'm not sure... i now have both the window and the gtk.drawing area active and it is a nice visual... i have the gtk.drawing setup to be 50% transparant and it makes it very clear which window you are actually dragging... 

> 
>     * When gridlock is canceled via keyboard or mouse button, the original geometry should be restored.
Agree 100%... so that basically means that we would need to store the original position before we start moving

> 
>     * There are X11 clients that ignore or do not react well to rapid geometry changes, so there should be a way to exclude live updates for clients by window classes and/or window name patterns
Not going to disagree here... i only have a few apps that is use continuously... none of them actually responded bad... so we are going to need a list of applications we don't want to do this for? or do we just stick with defaulting to off for the whole feature?

> 
>     * This feature should be optional with default-off
I can agree with this. Also see above.

**Comment by elangelo** [comment]
Made a small video of this... up to you if you want the GtkDrawingArea off or on... i think it looks pretty neat as it is...

https://youtu.be/H1D5rIB9_iQ

**Comment by bjorn-fischer** [comment]
Please hold on to this a bit, since I am preparing a more generalized version of "Only use offset for csd windows" which will include methods for setting the target window geometry.

**Pull request closed without merging**
